version: '3'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_USER: postgres
      POSTGRES_DB: mydatabase
    ports:
      - 5432:5432
    volumes:
      - ./data:/var/lib/postgresql/data

  backend:
    build: .
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - db
    environment:
      - DB_URL=jdbc:postgresql://db:5432/mydatabase
      - DB_USERNAME=postgres
      - DB_PASSWORD=mysecretpassword